apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
  - host: k8s-example.com
    http:
      paths:
      - path: /webapp
        backend:
          service:
            name: webapp-service
            port:
              number: 3000